// <auto-generated />
using System;
using GerenciaLeads.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciaLeads.Api.Migrations
{
    [DbContext(typeof(GerenciaLeadsContext))]
    partial class GerenciaLeadsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GerenciaLeads.Api.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Accepted")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = 5577421,
                            Accepted = "N",
                            Category = "Painters",
                            DateCreated = new DateTime(2022, 5, 31, 22, 52, 1, 27, DateTimeKind.Local).AddTicks(6285),
                            Description = "Need to paint 2 aluminum windows and a sliding glass door",
                            EmailAddress = "bill@test.com",
                            FullName = "Bill Test",
                            PhoneNumber = "1198765423456",
                            Price = 62m,
                            Suburb = "Yanderra 2574"
                        },
                        new
                        {
                            Id = 5588872,
                            Accepted = "N",
                            Category = "Interior Painters",
                            DateCreated = new DateTime(2022, 5, 31, 22, 52, 1, 27, DateTimeKind.Local).AddTicks(6301),
                            Description = "internal walls 3 colours",
                            EmailAddress = "craig@test.com",
                            FullName = "Craig Test",
                            PhoneNumber = "1198765423451",
                            Price = 49m,
                            Suburb = "Woolooware 2230"
                        },
                        new
                        {
                            Id = 5141895,
                            Accepted = "Y",
                            Category = "General Building Work",
                            DateCreated = new DateTime(2022, 5, 31, 22, 52, 1, 27, DateTimeKind.Local).AddTicks(6303),
                            Description = "Plaster exposed...",
                            EmailAddress = "fake@mailinator.com",
                            FullName = "Pete",
                            PhoneNumber = "0412345678",
                            Price = 26m,
                            Suburb = "Carramar 6031"
                        },
                        new
                        {
                            Id = 5121931,
                            Accepted = "Y",
                            Category = "Home Renovations",
                            DateCreated = new DateTime(2022, 5, 31, 22, 52, 1, 27, DateTimeKind.Local).AddTicks(6304),
                            Description = "There is a two ...",
                            EmailAddress = "another.fake@hipmail.com",
                            FullName = "Craig Test",
                            PhoneNumber = "04987654321",
                            Price = 32m,
                            Suburb = "Quinns Rock 6030"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
